server:
  port: 8083
spring:
  application:
    name: baiying_tongcai_user
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
cloud:
  config:
    discovery:
      enabled: true
      service-id: springcloud-config-server
    profile: dev
feign:
  hystrix:
    enabled: true