<<<<<<< HEAD
server:
  port: 8081
spring:
  application:
    name: springcloud-config-server
eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
  client:
   service-url:
    defaultZone: http://${eureka.instance.hostname}:${server.post}/eureka/
   register-with-eureka: false
=======
server:
  port: 8081
spring:
  application:
    name: springcloud-config-server
eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
  client:
   service-url:
    defaultZone: http://${eureka.instance.hostname}:${server.post}/eureka/
   register-with-eureka: false
>>>>>>> dd
   fetch-registry: false